---
title: "Untitled"
author: "Matt Ryan"
date: "2023-11-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- Need to run R_codeV6 or 7 first to get parameters loaded up.

```{r}
tmp <- modelOutputs
rownames(tmp) <- stateNames
```

```{r}
ind <- getIndicesForStateQuery(stateNames = stateNames, sex=c("f", "m"))
```

```{r}
tmp[ind,]|>apply(2, sum)
```

```{r}
tmp[ind[1],]
```




```{r}
ind_alb <- getIndicesForStateQuery(stateNames, genotype = "wAlbAB")
ind_mated_w_pip <- getIndicesForStateQuery(stateNames, genotype = "wAlbAB", mate = "wPip")
ind_mated_age <- getIndicesForStateQuery(stateNames, genotype = "wAlbAB", mate = "wAlbAB", mateStage = 2:20)
# PP <- state_vector[ind_alb[!(ind_alb %in% c(ind_mated_w_pip,ind_mated_age))]]
PP <- state_vector[ind_alb[!(ind_alb %in% c(ind_mated_w_pip))]]
M_ind <- getIndicesForStateQuery(names(PP), sex="m")
F_ind <- getIndicesForStateQuery(names(PP), sex="f", mate = "Unmated")
# PP[M_ind] <- PP[M_ind] + 20
# PP[F_ind] <- PP[F_ind] + 20

ode_defs <- function(t, y){
  
  dy <- rep(0, length(PP))
  names(dy) <- names(PP)
  
  immM_ind <- getIndicesForStateQuery(names(PP), sex = "immM")
  immF_ind <- getIndicesForStateQuery(names(PP), sex = "immF")
  imm_ind <-c(immM_ind, immF_ind)
  M_ind <- getIndicesForStateQuery(names(PP), sex="m")
  F_ind <- getIndicesForStateQuery(names(PP), sex="f", mate = "Unmated")
  F_M_ind <- getIndicesForStateQuery(names(PP), sex="f", mate= "wAlbAB")
  
  dy[immM_ind[1]] <- sum(y[F_M_ind]) * (femaleBirthRate[1]/2) * (I_max[1] - sum(y[imm_ind])) / (I_max[1]) - transitionRate_imm* y[immM_ind[1]]
  dy[immF_ind[1]] <- sum(y[F_M_ind]) * (femaleBirthRate[1]/2) * (I_max[1] - sum(y[imm_ind])) / (I_max[1]) - transitionRate_imm[1] * y[immF_ind[1]]
  
  # Immature transitions
  for(k in 2:length(immM_ind)){
    dy[immM_ind[k]] <-transitionRate_imm[1] * y[immM_ind[k-1]] - transitionRate_imm[1] * y[immM_ind[k]]
    dy[immF_ind[k]] <-transitionRate_imm[1] * y[immF_ind[k-1]] - transitionRate_imm[1] * y[immF_ind[k]]
  }
  
  #Male transitions
  dy[M_ind[1]] <- transitionRate_imm[1] * y[immM_ind[length(immM_ind)]] - (maleDeathRate[1] + 1) * y[M_ind[1]]
  for (k in 2:(length(M_ind) - 1)){
    dy[M_ind[k]] <- y[M_ind[k-1]] - (maleDeathRate[1] + 1) * y[M_ind[k]]
  }
  dy[M_ind[length(M_ind)]] <- y[M_ind[length(M_ind)-1]] - maleDeathRate[1] * y[M_ind[length(M_ind)]]
  
  # Female transitions
  
  dy[F_ind] <- transitionRate_imm[1] * y[immF_ind[length(immF_ind)]] - femaleDeathRate[1] * y[F_ind] - femaleMatingRateByPopulation[1] * y[F_ind] * sum(y[M_ind])
  
  for(k in 1:length(F_M_ind)){
    dy[F_M_ind[k]] <- femaleMatingRateByPopulation[1] * y[F_ind] * y[M_ind[k]] - femaleDeathRate[1] * y[F_M_ind[k]]
  }
  
  
  return(dy)
}
```

```{r}
sol <- pracma::ode23(ode_defs, t0 = 0, tfinal = 100, y0 = PP)
```

```{r}
tmp <- aggregateStates(names(PP), modelOutputs = t(sol$y), populationNames = "block01", genotypeNames = "wAlbAB")
```

```{r}
for(i in 1:length(tmp))
{
  plot(sol$t, tmp[[i]], xlab = "Days", ylab = "Population", main = names(ts)[[i]])  
  lines(sol$t, tmp[[i]])  
}
```


